# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

# Ursprungskod - Matris A
"A = np.arange(1, 16).reshape(3,5)"


In [ ]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
print("Dimension (antal axlar):", A.ndim) #two axes. Ax one rows Ax two kolumns.   
print("Form:", A.shape) #three rows, five colums  
print("Storlek:", A.size) 
print("Data typ:", A.dtype)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

# Ursprungskod - Matris B och C 
"B = np.arange(1, 10).reshape(3, 3)"
"C = np.ones((3, 3))*2"
"print(B)"
"print()"
"print(C)"

In [ ]:
import numpy as np
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matris B:")
print(B)
print()

print("Matris C:")
print(C)
print()

elementwise_subtraction = B - C
print("Elementvis Subtraktion:") 
print(elementwise_subtraction) 
print()

elementwise_multiplication = B * C
print("Elementvis Multiplikation:") 
print(elementwise_multiplication)
print()

matrix_multiplication = B @ C 
print("Matris Multiplikation:") 
print(matrix_multiplication)
print()


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

# Ursprungskod - Calculations
"B = np.arange(1, 10).reshape(3, 3)"
"print(B)"

In [ ]:
import numpy as np 
B = np.arange(1, 10).reshape(3, 3) 
print("Matris B:")
print(B)
print()

exp_B = np.exp(B) 
print("\nExponentiera B:") 
print(exp_B) 
print()

min_value = np.min(B) 
print("\nMinimivärde i hela matrisen:") 
print(min_value) 
print()

min_value_rows = np.min(B, axis=1) 
print("\nMinimivärde för varje rad:") 
print(min_value_rows)
print()

min_value_columns = np.min(B, axis=0) 
print("\nMinimivärde för varje kolumn:") 
print(min_value_columns)
print()

index_min_value = np.argmin(B) 
print("\nIndex för lägsta värde i hela tabellen:") 
print(index_min_value)
print()

index_min_value_rows = np.argmin(B, axis=1) 
print("\nIndex för lägsta värde för varje rad") 
print(index_min_value_rows)
print()

sum_all_elements = np.sum(B) 
print("\nSumma för alla element:") 
print(sum_all_elements)
print()

mean_columns = np.mean(B, axis=0) 
print("\nMedelvärde för varje kolumn:") 
print(mean_columns)
print()

median_columns = np.median(B, axis=0) 
print("\nMedianvärde för varje kolumn:") 
print(median_columns)
print()

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
print(A) kommer att skriva ut hela matrisen. 
A[1] kommer att selektera utskriften och bara skriva raden (hela raden) för den rad som har index 1.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

# Ursprungskod - Iteration elementvis
"A"
"for i in A:" "radvis iteration"
    print(i)"

In [ ]:
import numpy as np

# Matris A
"A = np.arange(1, 16).reshape(3,5)"

# Matris A (Två rader tre kolumner)
A = np.array([[1, 2, 3], [4, 5, 6]])

# Iterera elementvis
for element in A.flat:
    print(element)

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

# Ursprungskod
"a = np.arange(30"
"b = a.reshape((2, 3, -1))"
"print(a)"
print()
"print(b)"

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1)) #"2 block, 3 rader, 30 /(2 × 3)"
print(a)
print()

print(b)

# Svar:
1. Den skriver först ut en 1D array med 30 tal (a).
2. Den skriver sedan ut en array med två block. 
3. -1 talar om för NumPy att härleda dimensionen baserat på antalet element, dvs 30/(2 × 3) = 5
   (2, 3, 5)

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

# Ursprungskod - Broadkasting
"m1 = np.array([[1, 2], [3, 4]])"
"m2 = np.array([1, 1])"
"print(m1 + m2)"

In [ ]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])  # 2x2-array
m2 = np.array([1, 1])  # 1x2-array (en rad med två element)
print(m1 + m2)



Svar: Broadkasting metoden innebär att de mindre dimensionerna sträcks ut [[1+1, 2+1], [3+1, 4+1]] 

dvs [[2, 3], [4, 5]]

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

# Ursprungskod - Linjär algebra
"v1 = np.array([1, 2, 3])"
"print(v1 + 1)"

In [ ]:
v1 = np.array([1, 2, 3]) #En dimesionell array
print(v1 + 1)





Svar: [1+1, 2+1, 3+1]
dvs [2, 3, 4]

# Ursprungskod - Linjär algebra
"A = np.arange(1, 5).reshape(2,2)"
"print(A)"

"b = np.array([2, 2])"
"print(b)"

In [ ]:
A = np.arange(1, 5).reshape(2,2) #Skapar en matris som är 2*2. [[1, 2] [3, 4]]
print(A)
print()
b = np.array([2, 2]) #Endimisionell array med två element.  
print(b)

In [ ]:
Svar:
Matris A 2*2
[[1, 2] 
 [3, 4]]

b=[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

## Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan".



# Uppgift 10.1.1

Uppgift 10.1.1

x=(4,3) # En rad två kolumner 

a) Vilken dimension har vektorn x?
Svar: Vektorn  x = (4, 3) har dimension 2.

b) Beräkn 5x 
Svar: (5*4, 5*3) = (20,15)

c) Beräkna 3x
Svar:3x=3(4,3)=(12,9)

d) Beräkna 5x+3x
Svar: 5x+3x=(20,15)+(12,9)=(32,24)

e) Beräkna 8x 
Svar: 8x=8(4,3)=(32,24)

f) Beräkna 4x−x
Svar: 4x-x=(16, 12)-(4, 3) = (12, 9)

g) Beräkna x⊤  Vilken blir den nya dimensionen efter att transponeringen utförts?
Svar: Den nya dimensionen är 2*1 (2 rader och 1 kolumn). (1 rad två kolumner, kolumnvektor)

h) Är x+x⊤ definierat? 
Svar: Nej

i) Beräkna ∥x∥
Svar:(4*4 + 3*3) = roten ur 25 = 5 


# Uppgift 10.1.2

Uppgift 10.1.2

a) Vilken dimension har vektornv?
Svar: 4x1, kolumnvektor

b) Beräkna 2v. v= (3,7,0,11)
Svar: kolumnvektor 2v=(6,14,0,22)

c) Beräkna 5v + 2v 
Svar: kolumnvektor (21,49,0,77)

d) Beräkna 4v − 2v.
Svar: kolumnvektor (6,14,0,22)

e) Beräkna v⊤, vilken blir den nya dimensionen efter att
 transponeringen utförts? 
 Svar: radvektor (3,7,0,11) Dimension = (1, 4)

f) Beräkna ∥v∥ (Vi tar kvadratroten av summan av kvadraterna av vektorelementen, v= (3,7,0,11))
Svar: Roten ur 179 = ca 13.38


# Uppgift 10.1.3

Uppgift 10.1.3
Define vector v1 = (4,3,1,5) and v2 = (2,3,1,1).

a) Calculate ∥v1∥.
Svar: Roten ur 51 = ca 7.14

b) Calculate ∥v1 − v2∥
Svar:Roten ut 20 = cirka 4.47

-----------------------------------------

import numpy as np

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

difference = v1 - v2
norm_difference = np.linalg.norm(difference)

print("Difference (v1 - v2):", difference)
print("Norm of the difference (∥v1 - v2∥):", norm_difference)


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

 # Uppgift 10.2.1.

 Uppgift 10.2.1

Rowmatrix
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2,1]])
D = np.array([[3, 4], [4,3]])
I = np.array([[1, 0], [0,1]])

Columnmatrix
E = np.array([[1, 2]])

 (a) 2A
 (b) B −2A
 (c) 3C −2E
 (d) 2D −3C
 (e) D⊤ +2D
 (f) 2C⊤ −2D⊤
 (g) A⊤ −B
 (h) AC
 (i) CD
 (j) CB
 (k) CI
 (l) AB

In [2]:
#Answer:a
import numpy as np

A = np.array([[2, 1, -1], [1, -1, 1]])
result = 2 * A
print(result)


[[ 4  2 -2]
 [ 2 -2  2]]


In [4]:
#Answer:b

import numpy as np

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

result = B - 2 * A
print(result)



[[ 0 -4  3]
 [ 0 -2 -4]]


In [8]:
#Answer:c

import numpy as np

C = np.array([[1, 2], [2, 1]])
E = np.array([[1, 2]])

# Multiplicera matriserna
result = 3 * C - 2 * E
print(result)




[[ 1  2]
 [ 4 -1]]


In [10]:
#Answer: d

import numpy as np

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

result = 2 * D - 3 * C
print(result)


[[3 2]
 [2 3]]


In [12]:
#Answer:e

import numpy as np

D = np.array([[3, 4], [4, 3]])

# Transponera matris D
D_transpose = D.T

# Beräkna D⊤ + 2D
result = D_transpose + 2 * D
print(result)



[[ 9 12]
 [12  9]]


In [14]:
#Anser:f

import numpy as np

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

# Transponera matriserna
C_transpose = C.T
D_transpose = D.T

# Beräkna 2C⊤ - 2D⊤
result = 2 * C_transpose - 2 * D_transpose
print(result)



[[-4 -4]
 [-4 -4]]


In [16]:
#Ansver:g
# Går ej olika dimensioner matchar ej

import numpy as np

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

# Transponera matris A
A_transpose = A.T

# Skriv ut transponerad A och B
print("A^T:")
print(A_transpose)
print("\nB:")
print(B)

# Försök till direkt subtraktion (kommer inte att fungera p.g.a. olika dimensioner)
try:
    result = A_transpose - B
    print("\nA^T - B:")
    print(result)
except ValueError as e:
    print(f"Error: {e}")


A^T:
[[ 2  1]
 [ 1 -1]
 [-1  1]]

B:
[[ 4 -2  1]
 [ 2 -4 -2]]
Error: operands could not be broadcast together with shapes (3,2) (2,3) 


In [ ]:
#Answer:h
#Dimensionerna matchar ej för multiplikation.

#import numpy as np
#A = np.array([[2, 1, -1], [1, -1, 1]])
#C = np.array([[1, 2], [2,1]])
#print(A*C)



In [18]:
#Answer:i 

import numpy as np

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

# Beräkna matrisprodukten CD
result = np.dot(C, D)
print(result)




[[11 10]
 [10 11]]


In [20]:
#Answer:j

import numpy as np

C = np.array([[1, 2], [2, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

# Beräkna matrisprodukten CB
result = np.dot(C, B)
print(result)



[[  8 -10  -3]
 [ 10  -8   0]]


In [22]:
#Anwer:k

import numpy as np

C = np.array([[1, 2], [2, 1]])
I = np.array([[1, 0], [0, 1]])

# Beräkna matrisprodukten CI
result = np.dot(C, I)
print(result)




[[1 2]
 [2 1]]


#Answer:i 

A = np.array([[2, 1, -1], [1, -1, 1]]) 
B = np.array([[4, -2, 1], [2, -4, -2]])

Matrisprodukter kräver att dimensionerna är kompatibla 
för att beräkningen ska vara möjlig.


# Anteckningar Uppgift 10.2.1

import numpy as np

# Definiera radmatris
Detta är en radmatris med en rad och två kolumner.
Matematisk presentation B=(1, 2)

B_row = np.array([[1, 2]])
print("Radmatris (1x2):")
print(B_row)
print("Shape:", B_row.shape)


# Definiera kolumnmatris
En kolumnmatris har alltid en enda kolumn. 
Med andra ord består en kolumnmatris av flera rader men endast en kolumn. Varje element i matrisen ligger i sin egna rad.
Exemplet är en kolumnmatris med två rader och en kolumn.
Matematisk presentation B=(1/2)

B_col = np.array([[1], 
                  [2]])

print("\nKolumnmatris (2x1):")
print(B_col)
print("Shape:", B_col.shape)


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

#Ursprungskod
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [15]:
#Answer
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


#Ursprungskod
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [21]:
#Answer
import numpy as np
# The base attribute of a view returns the original array while it returns None for a copy.
v1 = np.arange(4)
v2 = v1[-2:]
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [ ]:
#Ursprungskod
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

Answer:
Understanding Views and Copies in NumPy
A view shares the same data buffer as the original array. Changes to the data in the view are reflected in the original array and vice versa.
A copy, however, creates a new data buffer. Changes made to the copy do not affect the original array.

Answer:
The base attribute confirms this: v2.base references v1, showing they share the same memory.
When you change a value in v2, the change is reflected in v1 because they share the same data buffer.
v2 = v1[-2:]

In [24]:
#Answer:
import numpy as np

v1 = np.arange(4)  # [0, 1, 2, 3]
v2 = v1[-2:]       # View of the last two elements: [2, 3]

# Check if `v2` is a view or a copy
print(v1.base)  # Output: None (original array)
print(v2.base)  # Output: <memory of v1> (shows that v2 is a view)

# Modify v2 and observe changes in v1
v2[-1] = 123     # Modify last element of v2
print(v1)        # Output: [0, 1, 2, 123] (v1 reflects the change)
print(v2)        # Output: [2, 123]       (v2 reflects the change)

None
[0 1 2 3]
[  0   1   2 123]
[  2 123]
